import { StyleSheet, Platform } from 'react-native';
import type { MD3Theme } from 'react-native-paper';

export function getRestockFormStyles(theme: MD3Theme) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    keyboardAvoidingView: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalContainer: {
      flex: 1,
      backgroundColor: theme.colors.background,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      padding: 16,
      marginTop: Platform.OS === 'ios' ? 44 : 20,
      maxHeight: '92%',
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 16,
      paddingBottom: 12,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.outline,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: '600',
      color: theme.colors.onSurface,
    },
    closeButtonCircle: {
      width: 32,
      height: 32,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      position: 'absolute',
      right: 0,
      top: 0,
      zIndex: 999999,
      elevation: 999999,
      backgroundColor: theme.colors.error,
    },
    closeButtonText: {
      color: '#fff',
      fontSize: 14,
      fontWeight: 'bold',
    },
    switchesContainer: {
      backgroundColor: theme.colors.surface,
      padding: 16,
      borderRadius: 12,
      marginBottom: 16,
      marginHorizontal: -8,
    },
    toggleContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 8,
      marginBottom: 4,
    },
    toggleText: {
      marginLeft: 12,
      fontSize: 15,
      color: theme.colors.onSurface,
    },
    searchContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 16,
      gap: 16,
    },
    searchInput: {
      flex: 1,
      backgroundColor: theme.colors.surface,
      color: theme.colors.onSurface,
      borderColor: theme.colors.outline,
    },
    viewButton: {
      padding: 8,
      borderRadius: 4,
      backgroundColor: theme.colors.primary,
    },
    viewButtonText: {
      fontSize: 14,
      fontWeight: '600',
      color: '#fff',
    },
    scrollContainer: {
      flexGrow: 1,
    },
    tableContainer: {
      flex: 1,
      borderWidth: 1,
      borderColor: theme.colors.outline,
      borderRadius: 12,
      overflow: 'hidden',
      marginBottom: 16,
      backgroundColor: theme.colors.surface,
    },
    tableContent: {
      flex: 1,
      width: '100%',
    },
    mobileTableContent: {
      minWidth: Platform.OS === 'web' ? '100%' : 'auto',
    },
    tableHeader: {
      flexDirection: 'row',
      backgroundColor: theme.colors.surface,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.outline,
      paddingVertical: 12,
    },
    headerCellContainer: {
      paddingVertical: 12,
      paddingHorizontal: 12,
      justifyContent: 'center',
      alignItems: 'flex-start',
    },
    headerCell: {
      fontSize: 15,
      fontWeight: '600',
      color: theme.colors.onSurfaceVariant,
    },
    tableBody: {
      flexGrow: 0,
      maxHeight: 300,
    },
    tableRow: {
      flexDirection: 'row',
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.outline,
      paddingVertical: 8,
      backgroundColor: theme.colors.surface,
    },
    cell: {
      paddingHorizontal: 12,
      paddingVertical: 10,
      justifyContent: 'center',
    },
    itemName: {
      fontSize: 15,
      fontWeight: '500',
      color: theme.colors.onSurface,
    },
    currentStock: {
      fontSize: 15,
      color: theme.colors.onSurfaceVariant,
    },
    input: {
      borderWidth: 1,
      borderColor: theme.colors.outline,
      borderRadius: 8,
      paddingHorizontal: 10,
      paddingVertical: 6,
      height: 36,
      backgroundColor: theme.colors.surface,
      textAlign: 'right',
      fontSize: 15,
      minWidth: 80,
      color: theme.colors.onSurface,
    },
    footer: {
      marginTop: 16,
      paddingTop: 16,
      borderTopWidth: 1,
      borderTopColor: theme.colors.outline,
      paddingBottom: Platform.OS === 'ios' ? 34 : 20,
      backgroundColor: theme.colors.background,
    },
    attachmentLabel: {
      fontSize: 16,
      fontWeight: '600',
      marginBottom: 12,
      color: theme.colors.onSurface,
    },
    receiptInput: {
      padding: 14,
      borderWidth: 1,
      borderColor: theme.colors.outline,
      borderRadius: 12,
      backgroundColor: theme.colors.surface,
      alignItems: 'center',
      marginBottom: 20,
      width: '100%',
    },
    receiptText: {
      color: theme.colors.onSurfaceVariant,
      fontSize: 14,
      flex: 1,
    },
    receiptPreviewContainer: {
      width: '100%',
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 4,
    },
    centerText: {
      textAlign: 'center',
    },
    applyButton: {
      padding: 16,
      borderRadius: 12,
      alignItems: 'center',
      marginBottom: Platform.OS === 'ios' ? 20 : 10,
      elevation: 2,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      backgroundColor: theme.colors.primary,
    },
    buttonText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '600',
      letterSpacing: 0.5,
    },
    headerContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 16,
      paddingHorizontal: 20,
      paddingTop: Platform.OS === 'ios' ? 40 : 20,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.outline,
      paddingBottom: 16,
      backgroundColor: theme.colors.background,
    },
    headerTitle: {
      fontSize: 24,
      fontWeight: 'bold',
      color: theme.colors.onSurface,
    },
    filePreviewContainer: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.7)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    filePreviewContent: {
      width: '90%',
      height: '80%',
      backgroundColor: theme.colors.surface,
      borderRadius: 10,
      position: 'relative',
      overflow: 'hidden',
      padding: 20,
    },
    filePreview: {
      width: '100%',
      height: '100%',
      marginTop: 20,
    },
    webSwitch: {
      cursor: 'pointer',
    },
    webSwitchTrack: {
      borderRadius: 12,
      padding: 2,
      width: 44,
      height: 24,
    },
    pdfPreviewContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
      backgroundColor: theme.colors.surface,
    },
    pdfPreviewText: {
      fontSize: 16,
      color: theme.colors.onSurfaceVariant,
      textAlign: 'center',
      marginBottom: 20,
    },
    pdfOpenButton: {
      padding: 12,
      borderRadius: 8,
      minWidth: 120,
      alignItems: 'center',
      backgroundColor: theme.colors.primary,
    },
    pdfOpenButtonText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '600',
    },
    inputContainer: {
      width: '100%',
    },
    errorText: {
      color: theme.colors.error,
      fontSize: 12,
      marginTop: 4,
    },
  });
}